# yml有个需要注意的地方，key和value要间隔一个空格，否则不会生效
spring:
  datasource:
    url: jdbc:mysql://172.22.23.160:3306/finance_shcis_credit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=true&verifyServerCertificate=false
    username: JR_dev
    password: dev160@sscf
  profiles:
    active: dev

server:
  port: 8086

#mybatis在配置xml路径的时候，注意classpath建立的目录是有层级的多个文件夹，而不是com.hu.bird.test这种一个文件夹
mybatis:
  typeAliasesPackage: com.hu.boot.bird.po
  mapperLocations: classpath:mybatis/*.xml

#
#mybatis-plus:
#  mapper-locations: classpath*:mybatis/*.xml
