# yml有个需要注意的地方，key和value要间隔一个空格，否则不会生效
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hu?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=true&verifyServerCertificate=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev

server:
  port: 8080

mybatis:
  typeAliasesPackage: com.hu.boot.bird.po
  mapperLocations: classpath:mybatis/*.xml