package com.hu.boot.bird.dao;

import com.hu.boot.bird.po.AwsAsin;
import com.hu.boot.bird.po.AwsAsinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AwsAsinDao {
    long countByExample(AwsAsinExample example);

    int deleteByExample(AwsAsinExample example);

    int deleteByPrimaryKey(Long id);

    int insert(AwsAsin record);

    int insertSelective(AwsAsin record);

    List<AwsAsin> selectByExample(AwsAsinExample example);

    AwsAsin selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") AwsAsin record, @Param("example") AwsAsinExample example);

    int updateByExample(@Param("record") AwsAsin record, @Param("example") AwsAsinExample example);

    int updateByPrimaryKeySelective(AwsAsin record);

    int updateByPrimaryKey(AwsAsin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(AwsAsin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(AwsAsin record);
}