package com.hu.boot.bird.aws.dao;

import com.hu.boot.bird.aws.po.AwsAsinRank;
import com.hu.boot.bird.aws.po.AwsAsinRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AwsAsinRankDao {
    long countByExample(AwsAsinRankExample example);

    int deleteByExample(AwsAsinRankExample example);

    int deleteByPrimaryKey(Long id);

    int insert(AwsAsinRank record);

    int insertSelective(AwsAsinRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin_rank
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AwsAsinRank selectOneByExample(AwsAsinRankExample example);

    List<AwsAsinRank> selectByExample(AwsAsinRankExample example);

    AwsAsinRank selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") AwsAsinRank record, @Param("example") AwsAsinRankExample example);

    int updateByExample(@Param("record") AwsAsinRank record, @Param("example") AwsAsinRankExample example);

    int updateByPrimaryKeySelective(AwsAsinRank record);

    int updateByPrimaryKey(AwsAsinRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin_rank
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AwsAsinRank> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin_rank
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AwsAsinRank> list, @Param("selective") AwsAsinRank.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin_rank
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(AwsAsinRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aws_asin_rank
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(AwsAsinRank record);
}